---
- name: Create {{ constraint.type }} constraint
  xml:
    path: "{{ xml_path }}"
    xpath: |-
      {%  if constraint.type == 'location' %}
      {%    set arg1 = constraint['rsc'] %}
      {%    set arg2 = constraint['node'] %}
      {%  elif constraint.type == 'colocation' %}
      {%    set arg1 = constraint['rsc'] %}
      {%    set arg2 = constraint['with-rsc'] %}
      {%  else %}
      {%    set arg1 = constraint['first'] %}
      {%    set arg2 = constraint['then'] %}
      {%  endif -%}
      {{  '/cib/configuration/constraints/rsc_%(type)s[@id="%(type)s-%(arg1)s-%(arg2)s-%(score)s"]'
      | format(type = constraint.type, arg1 = arg1, arg2 = arg2, score = constraint.score) }}
  check_mode: false

- name: Set constraint properties
  xml:
    path: "{{ xml_path }}"
    xpath: |-
      {%  if constraint.type == 'location' %}
      {%    set arg1 = constraint['rsc'] %}
      {%    set arg2 = constraint['node'] %}
      {%  elif constraint.type == 'colocation' %}
      {%    set arg1 = constraint['rsc'] %}
      {%    set arg2 = constraint['with-rsc'] %}
      {%  else %}
      {%    set arg1 = constraint['first'] %}
      {%    set arg2 = constraint['then'] %}
      {%  endif -%}
      {{  '/cib/configuration/constraints/rsc_%(type)s[@id="%(type)s-%(arg1)s-%(arg2)s-%(score)s"]'
      | format(type = constraint.type, arg1 = arg1, arg2 = arg2, score = constraint.score) }}
    attribute: "{{ attr_name }}"
    value: |-
      {%  if constraint[attr_name] is sameas(true) %}
      {{    'true' }}
      {%- elif constraint[attr_name] is sameas(false) %}
      {{    'false' }}
      {%- else %}
      {{    constraint[attr_name] }}
      {%- endif %}
  loop: "{{ constraint.keys() | difference(['type']) }}"
  loop_control:
    loop_var: attr_name
    label: "{{ '{' ~ attr_name ~ ': ' ~ constraint[attr_name] ~ '}' }}"
  check_mode: false
