---
- include_tasks: pre.yml

- name: Create group {{ pcmk_group.id }}
  xml:
    path: "{{ pcmk_config.path }}"
    xpath: "/cib/configuration/resources/group[@id='{{ pcmk_group.id }}']"
  check_mode: false
  run_once: true

- name: Create resources in group {{ pcmk_group.id }}
  include_tasks: any-resource.yml
  vars:
    resource_parent: '/cib/configuration/resources/group[@id="{{ pcmk_group.id }}"]'
    parent_id: "{{ pcmk_group.id }}"
    resource: "{{ item.value }}"
    resource_id: "{{ item.key }}"
  with_dict: "{{ pcmk_group.resources }}"
  run_once: true

- include_tasks: post.yml
