---
- name: Enable and start PCS daemon
  service:
    name: pcsd
    enabled: true
    state: started

- name: Generate a password for the user {{ pcmk_user }}
  set_fact:
    pcmk_password: "{{ ansible_machine_id | to_uuid }}"
  run_once: true
  when: pcmk_password is not defined

- name: Set password for the user {{ pcmk_user }}
  user:
    name: "{{ pcmk_user }}"
    system: true
#    password: "{{ pcmk_password | password_hash('sha512', ansible_hostname) }}"
    password: "{{ pcmk_password | password_hash('sha512') }}"

- name: Authenticate all nodes
  command: >
    pcs cluster auth
    {{ ansible_play_batch | join(' ') }}
    -u {{ pcmk_user }}
    -p {{ pcmk_password | quote }}
  run_once: true
  args:
    creates: /var/lib/pcsd/tokens

- name: Setup message bus
  run_once: true
  command: >
    pcs cluster setup --name {{ pcmk_cluster_name | quote }}
    {{  ansible_play_batch | join(' ') }}
    {%  for key, value in pcmk_votequorum.items() %}
    {%    if value is sameas(true) %}
    {%      set value = 1 %}
    {%    elif value is sameas(false) %}
    {%      set value = 0 %}
    {%    endif %}
    {{    '--%s=%s' | format(key, value) }}
    {%  endfor %}
  args:
    creates: /etc/corosync/corosync.conf

- name: Start all nodes
  service:
    name: "{{ inner_item }}"
    enabled: true
    state: started
  loop:
    - corosync
    - pacemaker
  loop_control:
    loop_var: inner_item

- include_tasks: pre.yml

- name: Configure cluster properties
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: /cib/configuration/crm_config/cluster_property_set[@id="cib-bootstrap-options"]
    parent_id: cib-bootstrap-options
  with_dict: "{{ pcmk_cluster_options }}"
  loop_control:
    loop_var: nvpair
    label: "{{ '{' ~ nvpair.key ~ ': ' ~ nvpair.value ~ '}' }}"
  run_once: true

- name: Configure resource defaults
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: /cib/configuration/rsc_defaults/meta_attributes[@id="rsc_defaults-options"]
    parent_id: rsc_defaults-options
  with_dict: "{{ pcmk_resource_defaults }}"
  loop_control:
    loop_var: nvpair
    label: "{{ '{' ~ nvpair.key ~ ': ' ~ nvpair.value ~ '}' }}"
  run_once: true

- include_tasks: post.yml
