---
- name: Install PCS package
  package:
    name: pcs
    state: installed

- name: Enable and start PCS daemon
  service:
    name: pcsd
    enabled: true
    state: started

- name: Generate a password for the user {{ pacemaker_user }}
  set_fact:
    pacemaker_password: "{{ ansible_machine_id | to_uuid }}"
  run_once: true
  when: pacemaker_password is not defined

- name: Set password for the user {{ pacemaker_user }}
  user:
    name: "{{ pacemaker_user }}"
    system: true
    password: "{{ pacemaker_password | password_hash('sha512', ansible_hostname) }}"

- name: Authenticate all nodes
  command: >
    pcs cluster auth
    {{ pacemaker_hosts | default(ansible_play_batch) | join(' ') }}
    -u {{ pacemaker_user }}
    -p {{ pacemaker_password }}
  run_once: true
  args:
    creates: /var/lib/pcsd/tokens

- name: Setup message bus
  run_once: true
  command: >
    pcs cluster setup --name {{ pacemaker_cluster_name }}
    {{  pacemaker_hosts | default(ansible_play_batch) | join(' ') }}
    {%  set vq_options = pacemaker_votequorum | default({}) %}
    {%  for key in vq_options.keys() | intersect(pacemaker_vq_keys) %}
    {%    if pacemaker_votequorum[key] is sameas(true) %}
    {%      set value = 1 %}
    {%    elif pacemaker_votequorum[key] is sameas(false) %}
    {%      set value = 0 %}
    {%    else %}
    {%      set value = pacemaker_votequorum[key] %}
    {%    endif %}
    {{    '--%s=%s' | format(key, value) }}
    {%  endfor %}
  args:
    creates: /etc/corosync/corosync.conf

- name: Start all nodes
  service:
    name: "{{ item }}"
    enabled: true
    state: started
  loop:
    - corosync
    - pacemaker

- name: Set up CIB XML
  run_once: true
  include_tasks: cib.yml
