---
- name: Create primitive {{ primitive.key }}
  xml:
    path: "{{ xml_path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive.key }}"]'
  check_mode: false

- name: Set {{ primitive.key }} resource agent
  xml:
    path: "{{ xml_path }}"
    xpath: '{{ primitive_parent }}/primitive[@id="{{ primitive.key }}"]'
    attribute: "{{ resource_attr.key }}"
    value: "{{ resource_attr.value }}"
  with_dict: "{{ primitive.value.resource }}"
  loop_control:
    loop_var: resource_attr
    label: "{{ '{' ~ resource_attr.key ~ ': ' ~ resource_attr.value ~ '}' }}"
  check_mode: false

- name: Configure attributes for {{ primitive.key }}
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: >-
      {{ primitive_parent ~
      ('/primitive[@id="%(key)s"]/instance_attributes[@id="%(key)s-instance_attributes"]'
      | format(key = primitive.key)) }}
    parent_id: "{{ primitive.key }}-instance_attributes"
  with_dict: "{{ primitive.value.options | default({}) }}"
  loop_control:
    loop_var: nvpair

- name: Configure meta attributes for {{ primitive.key }}
  include_tasks: nvpair.yml
  vars:
    nvpair_parent: >-
      {{ primitive_parent ~
      ('/primitive[@id="%(key)s"]/meta_attributes[@id="%(key)s-meta_attributes"]'
      | format(key = primitive.key)) }}
    parent_id: "{{ primitive.key }}-meta_attributes"
  with_dict: "{{ primitive.value.meta | default({}) }}"
  loop_control:
    loop_var: nvpair

- name: Configure operations for {{ primitive.key }}
  include_tasks: op.yml
  vars:
    op_parent: '{{ primitive_parent }}/primitive[@id="{{ primitive.key }}"]/operations'
    parent_id: "{{ primitive.key }}"
  loop: "{{ primitive.value.op | default([]) }}"
  loop_control:
    loop_var: op_properties
